version: '2.0'
services:
  server:
    image: distributedserver:1.0
    ports:
    - "8080"
  client:
    build: .
    environment:
        - DISTSERVER_HOST=server
        - DISTSERVER_PORT=8080